server:
  port: 8888
spring:
  application:
    name: config-server
  main:
    banner-mode: off
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

logging:
  level:
    root: warn
    com:
      mak:
        config: warn
