server:
  port: 7001

spring:
  application:
    name: students
  # config:
  #   import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka
