spring:
  application:
    name: discovery
  main:
    banner-mode: off
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    root: warn
    com:
      mak:
        config: warn
